//@ui5-bundle com/otisoft/favs/Favorites/Component-preload.js
sap.ui.require.preload({
	"com/otisoft/favs/Favorites/Component.js":function(){sap.ui.define(["sap/ui/core/UIComponent","sap/ui/Device","com/otisoft/favs/Favorites/model/models"],function(e,t,i){"use strict";return e.extend("com.otisoft.favs.Favorites.Component",{metadata:{manifest:"json"},init:function(){e.prototype.init.apply(this,arguments);this.getRouter().initialize();this.setModel(i.createDeviceModel(),"device")}})});
},
	"com/otisoft/favs/Favorites/controller/BaseController.js":function(){sap.ui.define(["sap/ui/core/mvc/Controller","sap/ui/core/routing/History","sap/ui/core/UIComponent","com/otisoft/favs/Favorites/model/formatter"],function(e,t,o,n){"use strict";return e.extend("com.otisoft.favs.Favorites.controller.BaseController",{formatter:n,getModel:function(e){return this.getView().getModel(e)},setModel:function(e,t){return this.getView().setModel(e,t)},getResourceBundle:function(){return this.getOwnerComponent().getModel("i18n").getResourceBundle()},navTo:function(e,t,o){this.getRouter().navTo(e,t,o)},getRouter:function(){return o.getRouterFor(this)},onNavBack:function(){var e=t.getInstance().getPreviousHash();if(e!==undefined){window.history.back()}else{this.getRouter().navTo("appHome",{},true)}}})});
},
	"com/otisoft/favs/Favorites/controller/MainView.controller.js":function(){sap.ui.define(["com/otisoft/favs/Favorites/controller/BaseController"],function(e,o){"use strict";return e.extend("com.otisoft.favs.Favorites.controller.MainView",{onInit:function(){},onPress:function(e){sap.m.URLHelper.redirect(e,true)}})});
},
	"com/otisoft/favs/Favorites/i18n/i18n.properties":'title=com.otisoft.favs.Favorites\nappTitle=com.otisoft.favs.Favorites\nappDescription=App Description\n',
	"com/otisoft/favs/Favorites/i18n/i18n_en.properties":'title=com.otisoft.favs.Favorites\nappTitle=com.otisoft.favs.Favorites\nappDescription=App Description\n',
	"com/otisoft/favs/Favorites/manifest.json":'{"_version":"1.21.0","sap.app":{"id":"com.otisoft.favs.Favorites","type":"application","i18n":"i18n/i18n.properties","applicationVersion":{"version":"1.0.0"},"title":"{{appTitle}}","description":"{{appDescription}}","dataSources":{"favorites_ds":{"uri":"model/favorites.json","type":"JSON"}}},"sap.ui":{"technology":"UI5","icons":{"icon":"","favIcon":"","phone":"","phone@2":"","tablet":"","tablet@2":""},"deviceTypes":{"desktop":true,"tablet":true,"phone":true}},"sap.ui5":{"flexEnabled":true,"rootView":{"viewName":"com.otisoft.favs.Favorites.view.MainView","type":"XML","async":true,"id":"idAppControl"},"dependencies":{"minUI5Version":"1.60.0","libs":{"sap.ui.core":{},"sap.m":{},"sap.ui.layout":{}}},"contentDensities":{"compact":true,"cozy":true},"models":{"i18n":{"type":"sap.ui.model.resource.ResourceModel","settings":{"bundleName":"com.otisoft.favs.Favorites.i18n.i18n"}},"favorites":{"type":"sap.ui.model.json.JSONModel","dataSource":"favorites_ds","preload":true,"settings":{"defaultBindingMode":"OneTime"}}},"resources":{"css":[{"uri":"css/style.css"}]},"routing":{"config":{"routerClass":"sap.m.routing.Router","viewType":"XML","viewPath":"com.otisoft.favs.Favorites.view","controlId":"idAppControl","controlAggregation":"pages","async":true},"routes":[{"name":"RouteMainView","pattern":"RouteMainView","target":["TargetMainView"]}],"targets":{"TargetMainView":{"viewType":"XML","viewLevel":1,"viewId":"idAppControl","viewName":"MainView"}}}}}',
	"com/otisoft/favs/Favorites/model/formatter.js":function(){sap.ui.define([],function(){"use strict";return{}});
},
	"com/otisoft/favs/Favorites/model/models.js":function(){sap.ui.define(["sap/ui/model/json/JSONModel","sap/ui/Device"],function(e,n){"use strict";return{createDeviceModel:function(){var i=new e(n);i.setDefaultBindingMode("OneWay");return i}}});
},
	"com/otisoft/favs/Favorites/view/MainView.view.xml":'<mvc:View\n\tcontrollerName="com.otisoft.favs.Favorites.controller.MainView"\n\tdisplayBlock="true"\n\txmlns="sap.m"\n\txmlns:mvc="sap.ui.core.mvc"\n\txmlns:layout="sap.ui.layout"\n><App id="app"><Page\n\t\t\tid="idFavPage"\n\t\t\tshowHeader="false"\n\t\t><layout:VerticalLayout\n\t\t\t\tid="_IDGenVerticalLayout1"\n\t\t\t\tclass="sapUiResponsiveMargin"\n\t\t\t><Title\n\t\t\t\t\tid="_IDGenTitle1"\n\t\t\t\t\ttitleStyle="H2"\n\t\t\t\t\ttext="Favorites"\n\t\t\t\t\tclass="sapUiTinyMarginBegin"\n\t\t\t\t/><layout:HorizontalLayout\n\t\t\t\t\tid="_IDGenHorizontalLayout1"\n\t\t\t\t\tallowWrapping="true"\n\t\t\t\t\tcontent="{favorites>/tiles}"\n\t\t\t\t><GenericTile\n\t\t\t\t\t\tid="_IDGenGenericTile1"\n\t\t\t\t\t\theader="{favorites>header}"\n\t\t\t\t\t\tsubheader="{favorites>subheader}"\n\t\t\t\t\t\tpress="onPress(${favorites>url})"\n\t\t\t\t\t\tclass="sapUiTinyMarginBegin sapUiTinyMarginTop"\n\t\t\t\t\t\theaderImage="{favorites>headerImage}"\n\t\t\t\t\t/></layout:HorizontalLayout><Title\n\t\t\t\t\tid="_IDGenTitle2"\n\t\t\t\t\ttitleStyle="H2"\n\t\t\t\t\ttext="Links"\n\t\t\t\t\tclass="sapUiTinyMarginBegin sapUiMediumMarginTop"\n\t\t\t\t/><layout:HorizontalLayout\n\t\t\t\t\tid="_IDGenHorizontalLayout2"\n\t\t\t\t\tallowWrapping="true"\n\t\t\t\t\tcontent="{favorites>/links}"\n\t\t\t\t><GenericTile\n\t\t\t\t\t\tid="_IDGenGenericTile2"\n\t\t\t\t\t\theader="{favorites>header}"\n\t\t\t\t\t\tsubheader="{favorites>subheader}"\n\t\t\t\t\t\tpress="onPress(${favorites>url})"\n\t\t\t\t\t\tmode="LineMode"\n\t\t\t\t\t\tclass="sapUiTinyMarginBegin"\n\t\t\t\t\t/></layout:HorizontalLayout></layout:VerticalLayout></Page></App></mvc:View>'
});
